import 'package:cupid_mentor/core/constants/localization_const.dart';
import 'package:cupid_mentor/core/core_object/localization_content.dart';

class AboutAuthor {
  static LocalizationContent aboutAuthor = const LocalizationContent(
    content: {
      LocalizationEnum.english:
          "Hello, I'm Mike, a developer from Vietnam. Recently, as I followed the news, I observed that modern life is becoming increasingly hectic and stressful. Many young people today seem to be swept away by the demands of work and finances, to the extent that they overlook a crucial part of life: finding their significant other. \nSearching for a partner and life companion has become a considerable challenge for them. They often face difficulties in communicating and interacting with the opposite sex and frequently struggle with effective ways to flirt or make connections.\n\nA clear illustration of this issue can be seen in countries like Japan and South Korea, where the number of single young people is rising. This trend may lead to more serious long-term consequences, such as an aging population, a shortage of dynamic young workers, and increased financial and social pressures.\n\nIn light of this situation and with the rapid advancements in artificial intelligence, I’ve come up with an idea for an app called Cupid Mentor. This app aims to support young people with valuable advice and practical suggestions, making it easier for them to navigate the complexities of dating, connect with others, and improve their communication skills. I hope this app will make a significant contribution to addressing the current challenges young people face in finding love and building meaningful relationships.",
      LocalizationEnum.vietnamese:
          'Xin chào, tôi là Mike, một nhà phát triển đến từ Việt Nam. Gần đây, khi theo dõi tin tức, tôi nhận thấy rằng cuộc sống hiện đại ngày càng bận rộn và căng thẳng. Nhiều người trẻ hiện nay dường như bị cuốn vào vòng xoáy công việc và tài chính, đến mức quên đi một phần quan trọng của cuộc sống: tìm kiếm một nửa của mình. Tìm kiếm người yêu và bạn đời có vẻ là 1 thử thách lớn với họ. Họ thường gặp khó khăn trong việc giao tiếp và trò chuyện với người khác giới, và nhiều khi không biết cách tán tỉnh hay làm quen một cách hiệu quả.\n\nMột minh chứng rõ ràng là ở các quốc gia như Nhật Bản và Hàn Quốc, tỷ lệ người trẻ độc thân đang gia tăng. Điều này có thể dẫn đến những hậu quả nghiêm trọng hơn trong tương lai, như vấn đề già hóa dân số, thiếu hụt nguồn lao động trẻ và năng động, gây ra nhiều áp lực tài chính và xã hội.\n\nTrước tình hình đó, với sự phát triển mạnh mẽ của trí tuệ nhân tạo, tôi đã nảy ra ý tưởng về một ứng dụng mang tên Cupid Mentor. Ứng dụng này được thiết kế nhằm hỗ trợ người trẻ bằng những lời khuyên giá trị, các gợi ý hợp lý, giúp họ dễ dàng hơn trong việc tán tỉnh, làm quen và giao tiếp với đối phương. Hy vọng rằng ứng dụng này sẽ góp phần nào vào việc giải quyết tình trạng thiếu hụt tình yêu và kết nối của giới trẻ hiện nay.',
      LocalizationEnum.japanese:
          'こんにちは、私はMike、Việt Nam出身の開発者です。最近、ニュースを見ていると、現代の生活がますます忙しく、ストレスが多いことに気づきました。多くの若者たちは仕事や財政の渦に巻き込まれ、人生の重要な部分である「パートナーを見つけること」を忘れてしまっているようです。恋人や人生の伴侶を見つけることが、彼らにとって大きな挑戦となっています。彼らは異性とのコミュニケーションや会話に苦労し、効果的にアプローチしたり、知り合う方法がわからないことがよくあります。\n\nこの問題は、日本や韓国などの国々で、若者の独身率が増加していることからも明らかです。これは将来的に、少子高齢化や若い労働力の不足、財政的および社会的な圧力の増大など、深刻な影響を引き起こす可能性があります。\n\nこの状況に対処するため、人工知能の急速な発展を受けて、「Cupid Mentor」というアプリのアイデアを思いつきました。このアプリは、若者たちがより良い恋愛関係を築き、異性とコミュニケーションを取るのを助けるために、貴重なアドバイスや実用的な提案を提供します。このアプリが、現在の若者たちの愛やつながりの不足を解決する一助となることを願っています。',
    },
  );
}
