class Personalities {
  static const List<String> personalities = [
    'Honest',
    'Ambitious',
    'Adventurous',
    'Brave',
    'Cheerful',
    'Witty',
    'Generous',
    'Aggression',
    'Artistic',
    'Calm',
    'Bold',
    'Charming',
    'Confident',
    'Easygoing',
    'Affectionate',
    'Cautious',
    'Arrogant',
    'Optimistic',
    'Sociable',
    'Intelligent',
    'Adaptable',
    'Bossy',
    'Bright',
    'Anxious',
  ];
}
